stages:
  - build
  - publish

## build ##

build:debian:
  tags:
    - aptly
  stage: build
  script:
    - sudo apt-get -y --no-install-recommends install build-essential fakeroot
    - sudo apt-get -y --no-install-recommends build-dep ./
    - dpkg-buildpackage -us -uc -rfakeroot
    - mv ../*_*.* .
  artifacts:
    expire_in: 2 weeks
    paths:
      - '*_*.*'

build:centos:
  tags:
    - aptly
  stage: build
  script:
    - sudo apt-get -y --no-install-recommends install rpm
    - rpmbuild -D"%_topdir $PWD" -D"%_sourcedir $PWD" -ba credativ-repo.spec
    - rpm --addsign RPMS/noarch/*.rpm SRPMS/*.rpm
  artifacts:
    expire_in: 2 weeks
    paths:
      - RPMS/*/*.rpm
      - SRPMS/*.rpm

## publish ##

publish:stretch-test: &publish_debian
  tags:
    - aptly
  stage: publish
  dependencies:
    - build:debian
  script:
    - aptly repo add $dist *.dsc *.deb
    - aptly publish update $dist
    - sync_packages.sh
  variables:
    dist: stretch-test

publish:stretch-stable:
  <<: *publish_debian
  variables:
    dist: stretch-stable
  when: manual

publish:bionic-test:
  <<: *publish_debian
  variables:
    dist: bionic-test

publish:bionic-stable:
  <<: *publish_debian
  variables:
    dist: bionic-stable
  when: manual

publish:el7-test: &publish_centos
  tags:
    - aptly
  stage: publish
  dependencies:
    - build:centos
  script:
    - cp RPMS/noarch/*.rpm ~/postgresql/yum/$dist/noarch
    - cp SRPMS/*.rpm ~/postgresql/yum/$dist/src
    - cd
    - make $dist
  variables:
    dist: el7-test

publish:el7:
  <<: *publish_centos
  variables:
    dist: el7
  when: manual
